server {
    listen 80;
    server_name mx.nightyu.com;
    root /opt/moemail-smtp-gateway/acme-webroot;

    location ^~ /.well-known/acme-challenge/ {
        default_type text/plain;
        try_files $uri =404;
    }

    location / {
        return 204;
    }
}
